### ISSUE TITLE
Bind crypto_pwhash (scrypt)

### ISSUE THREAD

**Issue by dsheets** [dsheets/ocaml-sodium#16]
See also http://doc.libsodium.org/password_hashing/README.html.

**Comment by whitequark** [comment]
>A high-level crypto_pwhash_*() API is intentionally not defined until the Password Hashing Competition is over.

Which is why I did not bind it in the first place.

**Comment by dsheets** [comment]
<https://password-hashing.net/timeline.html> says 2015Q2 so we wait.

**Comment by cfcs** [comment]
Argon2 has been selected as the winner, "a formal announcement will be available at the end of 2015 Q3"

**Comment by dsheets** [comment]
This arrived in #38.
