### ISSUE TITLE
chacha20

### ISSUE THREAD

**Issue by buzzheavyyear** [dsheets/ocaml-sodium#18]
Any chance of also exposing chacha20, as well as salsa20?

**Comment by dsheets** [comment]
I think this is a reasonable idea. I would accept patches to do this but won't have time to work on it myself until the end of March.

**Comment by buzzheavyyear** [comment]
OK, I'll give it a go. Would you mind if I expose Hash256 too?

Incidentally, I've just cloned ocaml-sodium and tried to make:

'''
OCAML_LIB_DIR=/home/nick/.opam/system/lib/ctypes ocamlbuild -use-ocamlfind -classic-display  lib/sodium.cma lib/sodium.cmxa
ocamlfind ocamlopt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
ocamlfind ocamldep -package ctypes.stubs -modules lib_gen/sodium_bindgen.ml > lib_gen/sodium_bindgen.ml.depends
ocamlfind ocamldep -package ctypes.stubs -modules lib_gen/sodium_bindings.ml > lib_gen/sodium_bindings.ml.depends
ocamlfind ocamldep -package bytes -package bigarray -package ctypes.stubs -modules lib/sodium_storage.ml > lib/sodium_storage.ml.depends
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_storage.cmo lib/sodium_storage.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib_gen -I lib -o lib_gen/sodium_bindings.cmo lib_gen/sodium_bindings.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib_gen -I lib -o lib_gen/sodium_bindgen.cmo lib_gen/sodium_bindgen.ml
ocamlfind ocamlc -linkpkg -package ctypes.stubs lib/sodium_storage.cmo lib_gen/sodium_bindings.cmo lib_gen/sodium_bindgen.cmo -o lib_gen/sodium_bindgen.byte
lib_gen/sodium_bindgen.byte
ocamlfind ocamlc -I /home/nick/.opam/system/lib/ctypes -ccopt '--std=c99 -Wall -pedantic -Werror -Wno-pointer-sign' -c lib/sodium_stubs.c
+ ocamlfind ocamlc -I /home/nick/.opam/system/lib/ctypes -ccopt '--std=c99 -Wall -pedantic -Werror -Wno-pointer-sign' -c lib/sodium_stubs.c
lib/sodium_stubs.c:2:37: fatal error: ctypes/cstubs_internals.h: No such file or directory
 #include "ctypes/cstubs_internals.h"
                                     ^
compilation terminated.
Command exited with code 2.
'''

**Comment by dsheets** [comment]
You'll need ctypes master for now.

**Comment by buzzheavyyear** [comment]
Finally got back to this - I've added StreamChaCha20 as a module (yes, my ocaml is still at the nursery level - not ready/able yet to functorise Stream), and after doing a:

opam pin -k git add sodium .

I get a  Error: Unbound module Sodium.StreamChaCha20.

Apologies, I know this is hand-holding, but I really am pulling out my hair over this. What have I missed out?

**Comment by dsheets** [comment]
Is it in the mli?

**Comment by buzzheavyyear** [comment]
Definitely in the mli, bindings etc. I've deleted any reference to sodium in my ~/.opam too. The only thing I can think of is to delete the ~/.opam dir, reload everything except for ocaml-sodium and then pin the local one and see what happens.

**Comment by dsheets** [comment]
`opam update`? Is it at the top level of the module (the path you expect)? Are you getting this error during a compile or using the toplevel? If you're trying to use it as an opam/ocamlfind package, have you installed it? Have you loaded the env vars for the current switch with ```eval `opam config env` ```?

**Comment by buzzheavyyear** [comment]
when I do an opam update, it tells me it's fetching the local ocaml-sodium.

when I compile, it accepts any references to existing ocaml-sodium modules, which precede the new modules I've included.

my opam environment is correctly set up with eval opam config env via .bashrc

Running make, I get the following -

'''
ocamlbuild -use-ocamlfind -pkg cstruct -pkg mirage-types -pkg sha -pkg sodium -pkg oUnit -I lib test_cs3a.native
ocamlfind ocamlc -c -package oUnit -package sodium -package sha -package mirage-types -package cstruct -I lib -o lib/cs3a.cmo lib/cs3a.ml
+ ocamlfind ocamlc -c -package oUnit -package sodium -package sha -package mirage-types -package cstruct -I lib -o lib/cs3a.cmo lib/cs3a.ml
File "lib/cs3a.ml", line 53, characters 17-49:
Error: Unbound module Sodium.StreamChaCha20
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.
  
  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:
  
      true: -traverse
      <dir1> or <dir2>: traverse
      
make: *** [all] Error 10

MAKE FAILED (exit value 2, total time: 3s)

'''

**Comment by buzzheavyyear** [comment]
- and compiling ocaml-sodium completes without error too - 

```
OCAML_LIB_DIR=/home/nick/.opam/system/lib/ctypes ocamlbuild -use-ocamlfind -classic-display  lib/sodium.cma lib/sodium.cmxa
ocamlfind ocamlopt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
ocamlfind ocamldep -package ctypes.stubs -modules lib_gen/sodium_bindgen.ml > lib_gen/sodium_bindgen.ml.depends
ocamlfind ocamldep -package ctypes.stubs -modules lib_gen/sodium_bindings.ml > lib_gen/sodium_bindings.ml.depends
ocamlfind ocamldep -package bytes -package bigarray -package ctypes.stubs -modules lib/sodium_storage.ml > lib/sodium_storage.ml.depends
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_storage.cmo lib/sodium_storage.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib_gen -I lib -o lib_gen/sodium_bindings.cmo lib_gen/sodium_bindings.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib_gen -I lib -o lib_gen/sodium_bindgen.cmo lib_gen/sodium_bindgen.ml
ocamlfind ocamlc -linkpkg -package ctypes.stubs lib/sodium_storage.cmo lib_gen/sodium_bindings.cmo lib_gen/sodium_bindgen.cmo -o lib_gen/sodium_bindgen.byte
lib_gen/sodium_bindgen.byte
ocamlfind ocamlc -I /home/nick/.opam/system/lib/ctypes -ccopt '--std=c99 -Wall -pedantic -Werror -Wno-pointer-sign' -c lib/sodium_stubs.c
mv sodium_stubs.o lib/sodium_stubs.o
ocamlfind ocamlmklib -o lib/sodium_stubs -lsodium lib/sodium_stubs.o
ocamlfind ocamldep -package bytes -package bigarray -package ctypes.stubs -modules lib/sodium.mli > lib/sodium.mli.depends
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium.cmi lib/sodium.mli
ocamlfind ocamldep -package bytes -package bigarray -package ctypes.stubs -modules lib/sodium.ml > lib/sodium.ml.depends
cp -p lib_gen/sodium_bindings.ml lib/sodium_bindings.ml
ocamlfind ocamldep -package bytes -package bigarray -package ctypes.stubs -modules lib/sodium_bindings.ml > lib/sodium_bindings.ml.depends
ocamlfind ocamldep -package bytes -package bigarray -package ctypes.stubs -modules lib/sodium_generated.ml > lib/sodium_generated.ml.depends
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_bindings.cmo lib/sodium_bindings.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_generated.cmo lib/sodium_generated.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium.cmo lib/sodium.ml
ocamlfind ocamlc -a -dllib -lsodium_stubs lib/sodium_storage.cmo lib/sodium_bindings.cmo lib/sodium_generated.cmo lib/sodium.cmo -o lib/sodium.cma
ocamlfind ocamlopt -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_storage.cmx lib/sodium_storage.ml
ocamlfind ocamlopt -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_bindings.cmx lib/sodium_bindings.ml
ocamlfind ocamlopt -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_generated.cmx lib/sodium_generated.ml
ocamlfind ocamlopt -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium.cmx lib/sodium.ml
ocamlfind ocamlopt -a -cclib -lsodium_stubs -cclib -lsodium lib/sodium_storage.cmx lib/sodium_bindings.cmx lib/sodium_generated.cmx lib/sodium.cmx -o lib/sodium.cmxa

MAKE SUCCESSFUL (total time: 16s)

```

**Comment by dsheets** [comment]
Ah, this `lib/cs3a.ml` is being built separately from the library. The `-pkg sodium` and `-package sodium` lines are to use the findlib package. You need to do `opam install sodium` (with the pin in place) to get access to the modified package. If you don't want to do this, you can link/include the `_build/lib` directory in the ocaml-sodium source tree directly.

**Comment by buzzheavyyear** [comment]
Sorry, should have been clearer about cs3a.ml.

But I think I have already done this, and error is still there -

```nick@wotan:~$ opam update
[default] Downloading https://opam.ocaml.org/urls.txt
[default] Downloading https://opam.ocaml.org/index.tar.gz
Updating ~/.opam/repo/compiler-index ...
Updating ~/.opam/compilers/ ...
Updating ~/.opam/repo/package-index ...
Updating ~/.opam/packages/ ...
[sodium] Fetching /home/nick/github/ocaml-sodium
nick@wotan:~$ opam install sodium

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[sodium] Fetching /home/nick/github/ocaml-sodium
[NOTE] Package sodium is already installed (current version is 0.4.0).
nick@wotan:~$ 
```

**Comment by buzzheavyyear** [comment]
- with ```opam list``` giving

```
nick@wotan:~$ opam list
# Installed packages for system:
....
shared-memory-ring           1.1.1  Shared memory rings for RPC and bytestream c
sodium                       0.4.0 (pinned)  Binding to libsodium UNAUDITED
ssl                          0.4.7  Bindings for OpenSSL
....
nick@wotan:~$ 
```

**Comment by dsheets** [comment]
Did you commit your modifications to the repository? `-k git` means that opam will attempt to check out the repo. Do your mods come up when you do `#show_module Sodium` in a toplevel?

**Comment by buzzheavyyear** [comment]
Ahhhh Noooooo. You're a star - I haven't done this - I'll do this. I owe you a beer (at least!). Thanks.

Actually, just one more, small question - I copied Hash to Hash256 and added _init, _update and _final to the bindings - these signatures are exported in the libsodium C headers. When I compile the ocaml-sodium library I get the following error

```
OCAML_LIB_DIR=/home/nick/.opam/system/lib/ctypes ocamlbuild -use-ocamlfind -classic-display  lib/sodium.cma lib/sodium.cmxa
ocamlfind ocamldep -package ctypes.stubs -modules lib_gen/sodium_bindgen.ml > lib_gen/sodium_bindgen.ml.depends
ocamlfind ocamldep -package ctypes.stubs -modules lib_gen/sodium_bindings.ml > lib_gen/sodium_bindings.ml.depends
ocamlfind ocamldep -package bytes -package bigarray -package ctypes.stubs -modules lib/sodium_storage.ml > lib/sodium_storage.ml.depends
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_storage.cmo lib/sodium_storage.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib_gen -I lib -o lib_gen/sodium_bindings.cmo lib_gen/sodium_bindings.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib_gen -I lib -o lib_gen/sodium_bindgen.cmo lib_gen/sodium_bindgen.ml
+ ocamlfind ocamlc -c -bin-annot -safe-string -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib_gen -I lib -o lib_gen/sodium_bindgen.cmo lib_gen/sodium_bindgen.ml
findlib: [WARNING] Interface sodium_bindings.cmi occurs in several directories: lib, lib_gen
ocamlfind ocamlc -linkpkg -package ctypes.stubs lib/sodium_storage.cmo lib_gen/sodium_bindings.cmo lib_gen/sodium_bindgen.cmo -o lib_gen/sodium_bindgen.byte
lib_gen/sodium_bindgen.byte
ocamlfind ocamlmklib -o lib/sodium_stubs -lsodium lib/sodium_stubs.o
ocamlfind ocamldep -package bytes -package bigarray -package ctypes.stubs -modules lib/sodium.mli > lib/sodium.mli.depends
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium.cmi lib/sodium.mli
ocamlfind ocamldep -package bytes -package bigarray -package ctypes.stubs -modules lib/sodium.ml > lib/sodium.ml.depends
cp -p lib_gen/sodium_bindings.ml lib/sodium_bindings.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_bindings.cmo lib/sodium_bindings.ml
ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_generated.cmo lib/sodium_generated.ml
+ ocamlfind ocamlc -c -bin-annot -safe-string -package bytes -package bigarray -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/sodium_generated.cmo lib/sodium_generated.ml
File "lib/sodium_generated.ml", line 463, characters 2-136:
Warning 11: this match case is unused.
File "lib/sodium_generated.ml", line 477, characters 2-93:
Warning 11: this match case is unused.
File "lib/sodium_generated.ml", line 1:
Error: Some fatal warnings were triggered (2 occurrences)
Command exited with code 2.
make: *** [all] Error 10

MAKE FAILED (exit value 2, total time: 3s)
```
If I look at the errors in the sodium_generated.ml file I can see that the signatures of the match cases in question are generated twice, both identical, eg line 463 gives 

```
| "crypto_hash_sha256_final",
  CI.Function
    (CI.Pointer x56,
     CI.Function (CI.OCaml CI.Bytes, CI.Returns (CI.Primitive CI.Int))) ->
  (fun x55 x57 -> caml__71_crypto_hash_sha256_final (CI.cptr x55) x57)
```

I've noticed that for other bindings (that compile), there are two, different signatures.

The sodium_bindings.ml code is

```
  module Hash256 = struct
    let primitive = "sha256"
    let prefix    = "crypto_hash_"^primitive

    let sz_query_type = void @-> returning size_t
    let hashbytes     = F.foreign (prefix^"_bytes") sz_query_type

    type hashstate
    let hashstate = structure (prefix^"_state")
      let (-:) ty label = field hashstate label ty
      let state   = array 8 uint32_t    -: "state"
      let count   = array 2 uint32_t    -: "count"
      let buf     = array 64 char       -: "buf"
    let () = seal (hashstate : hashstate structure typ)
    type hashstate_t = hashstate structure ptr
    let hashstate_t = ptr hashstate

    let make_state    = addr (make hashstate)

    module Make(T: Sodium_storage.S) = struct
      let hash          = F.foreign (prefix)
                                    (ocaml_bytes @-> T.ctype @-> ullong @-> returning int)

      let init          = 
                          F.foreign (prefix^"_init")
                                    (hashstate_t @-> returning int)

      let update          = F.foreign (prefix^"_update")
                                    (hashstate_t @-> T.ctype @-> ullong @-> returning int)

      let final          = F.foreign (prefix^"_final")
                                    (hashstate_t @-> ocaml_bytes @-> returning int)
    end
  end
'''

Apologies, again, for using up your time.

**Comment by dsheets** [comment]
`init` and `final` aren't dependent on the functor argument type `T.ctype`. Either a portion of their type should be dependent or they should be moved into the generic section of the module outside of the functor.

**Comment by buzzheavyyear** [comment]
Thanks for your help - very grateful.

**Comment by dsheets** [comment]
@cfcs has contributed a basic `crypto_generichash` binding and I have added stream support for the 0.5.0 release pending ocaml/opam-repository#4393. Does this satisfy your use case or do you still require chacha20/Hash256 bindings?

**Comment by buzzheavyyear** [comment]
The generic_hash should be fine - thanks for all of the above help!
