### ISSUE TITLE
Bind crypto_generichash_blake2b

### ISSUE THREAD

**Issue by cfcs** [dsheets/ocaml-sodium#21]
It would be extremely useful to have a binding to `crypto_generichash_blake2b` (or `crypto_generichash`).

**Comment by dsheets** [comment]
This was done in #26. By the way, there is something wrong with your git email and GitHub account email such that they don't link your commits to your user id.

**Comment by cfcs** [comment]
I don't think I have an email configured, am I missing out on some neat github feature? :-(

**Comment by dsheets** [comment]
https://github.com/dsheets/ocaml-sodium/commits/master lists your commits but your username isn't linkificated. Also https://github.com/dsheets/ocaml-sodium/graphs/contributors doesn't list you as a contributor.

**Comment by cfcs** [comment]
Ah, ok, thank you for clarifying.
It seems silly that Github wouldn't link commits from my account to me, but it doesn't seem super important - perhaps they'll fix that sometime (creating a new github account to work around this seems like overkill).

**Comment by dsheets** [comment]
I think the issue is that they don't know they are from you because your user can be pushing commits from other people (e.g. mirroring Linux or what I just did). Because of that, they use your email as a global identifier.
