### ISSUE TITLE
Automatic key erasure / "wiping"

### ISSUE THREAD

**Issue by cfcs** [dsheets/ocaml-sodium#24]
I just noticed that many of the bindings expose a "wipe" function:
```ocaml
let wipe str =
  C.memzero (Storage.Bytes.to_ptr str) (Storage.Bytes.len_size_t str)
```

It seems to me like it could be useful to automatically wipe keys as they are garbage collected using a `Gc` callback by adding a `Gc` finalization hook:
 ```ocaml
Gc.finalise (fun key -> wipe key) my_key
```

`Ctypes` has something similar for its `Ctypes.allocate` functions:
```ocaml
val allocate : ?finalise:('a ptr -> unit) -> 'a typ -> 'a -> 'a ptr
```

-----

Documentation for `Gc`:
http://caml.inria.fr/pub/docs/manual-ocaml/libref/Gc.html

Documentation for `Ctypes`:
http://ocamllabs.github.io/ocaml-ctypes/Ctypes.html

Disclaimer:
I'm not **super** familiar with OCaml internals, so maybe this is silly / not effective, but I thought I'd post the idea here and hear your comments. Is this a viable option, at least for cases where the keys are never converted away from `bytes`?

**Comment by dsheets** [comment]
This seems like a nice idea but I wonder about its utility. Users should not rely on garbage collection to zero their keys. GC should be treated as basically non-deterministic and may not occur at all! I think users should treat *any* un-wiped extra retention of key material as a possible issue and not feel satisfied that the GC will ensure security properties.

This is just my intuition regarding this issue and I may very well have overlooked something. @whitequark what say you?

**Comment by whitequark** [comment]
Agreed.

**Comment by cfcs** [comment]
I realize that without some sort of "taint tagging" (for lack of better words), completely getting rid of all sensitive data is not an easy job -- but I think we should attempt to cover as many cases as possible.

I had a look at the `Gc` module by the way, it seems like GC can be forced with `Gc.full_major ()`:
> `val full_major : unit -> unit`
> Do a minor collection, finish the current major collection cycle, and perform a complete new cycle. This will collect all currently unreachable blocks.

**Comment by cfcs** [comment]
This might be slightly related: https://github.com/dsheets/ocaml-sodium/issues/25

I'm trying to make a PR for that now, but it needs some massaging - my application of `Ctypes.foreign_value` is currently trying to bind a pointer to the `MCL_CURRENT` and `MCL_FUTURE` constants:
```
lib/sodium_stubs.c:33:15: error: lvalue required as unary ‘&’ operand
    int* x24 = &MCL_CURRENT;
```

**Comment by whitequark** [comment]
That's a really good way to kill your performance. Besides, this won't even work on alternative implementations such as ocamljava.

A behavior for a finalizer that I would actually prefer is crashing the process if the key material is not wiped. Though it might be too extreme for most users. (In general, if someone can read memory of your process, it is almost always already too late.)

mlockall requires root. For the same reasons, I am very much not convinced it is a good security measure, simply because the intersection of the cases where someone has access to your swap and where mlockall() would have helped is vanishingly small.

**Comment by cfcs** [comment]
Alright, I hear your arguments -- I guess you're right.

Crashing the process could generate a core dump though, that's probably not very desirable either. :(
