### ISSUE TITLE
Add binding to libc mlockall

### ISSUE THREAD

**Issue by cfcs** [dsheets/ocaml-sodium#25]
Since the `Unix` library doesn't bind `mlockall`, perhaps we should at least offer a binding since we're handling sensitive data, and most users of `ocaml-sodium` will presumably want to disable swapping to disk.

Documentation for `mlockall`:
Linux: http://linux.die.net/man/2/mlockall
FreeBSD: http://www.unix.com/man-page/freebsd/2/mlockall/
OpenBSD: http://nixdoc.net/man-pages/OpenBSD/man2/mlockall.2.html

Thoughts?

**Comment by cfcs** [comment]
Closing as per the discussion in https://github.com/dsheets/ocaml-sodium/issues/24

**Comment by dsheets** [comment]
This functionality should definitely be bound and available via opam. I don't think that this library is the best place to expose it. In particular, binding `mlockall` would introduce a POSIX dependency and then we'd have to introduce a subpackage for the `unix` bindings. Please, let me know if and where you write the bindings to `mlockall` and friends. If you don't do it, I probably will, eventually.

**Comment by yallop** [comment]
From https://github.com/dsheets/ocaml-sodium/issues/24#issuecomment-102617277:

> my application of Ctypes.foreign_value is currently trying to bind a pointer to the MCL_CURRENT and MCL_FUTURE constants:

Right: `foreign_value` is for binding addressable run-time values in a C library.  For retrieving the values of compile-time constants you need to use the [`constant`](https://github.com/ocamllabs/ocaml-ctypes/blob/86b46a338d90b828b3c6064a955ac5baf78ffc1a/src/cstubs/cstubs.mli#L17-L30) function instead.

**Comment by cfcs** [comment]
Thanks @yallop!

@dsheets : I will!
