### ISSUE TITLE
Possible issue with make test on osx/homebrew

### ISSUE THREAD

**Issue by gregrperkins** [dsheets/ocaml-sodium#3]
When I used `brew install nacl`, it unpacked the headers and lib files into the `$(brew --prefix)/{include,lib}` directories, which caused the <nacl/crypto_box.h> include to fail.

I had to modify the makefile to thread flags through to ${CC} and use 

```
-L`brew --prefix`/lib -I`brew --prefix`/include
```

**Comment by dsheets** [comment]
Is this still an issue with non-standard `brew` prefix locations?

**Comment by gregrperkins** [comment]
Brew has changed dramatically since this was filed; I'd guess it's no
longer a relevant task.
