### ISSUE TITLE
incorrect ctypes version bound for (sodium > 0.4)?

### ISSUE THREAD

**Issue by gasche** [dsheets/ocaml-sodium#33]
The [opam-builder results](http://opam.ocamlpro.com/builder/html/report-full.html#sodium) for sodium currently show that versions above 0.4 (that is 0.4.1, 0.5) fail to build. The build failure looks like in this report <http://opam.ocamlpro.com/builder/html/sodium/sodium.0.5.0/57f96b30bff10fbb79b7d53086df011e>, with sodium 5.0, ctypes 0.8.0 and ocaml 4.01.0 (see the report for the other versions of the dependencies).

```
# File "lib_gen/sodium_bindings.ml", line 26, characters 46-71:
# Error: This expression has type
#          (unit -> unit) Ctypes.fn = (unit -> unit) Ctypes_static.fn
#        but an expression was expected of type ('a -> 'b) F.fn
# Command exited with code 2.
```

I suppose that this means the version bound on ctypes is not strict enough. What would be correct version constraints?

**Comment by yallop** [comment]
I think the released versions  should be constrained to ctypes `< 0.6.0`.  See also #32 (merged but unreleased), which adds support for more recent ctypes versions.

**Comment by gasche** [comment]
Thanks, I'll fix the released package descriptions.
