### ISSUE TITLE
Change of maintainer

### ISSUE THREAD

**Issue by cyberhuman** [dsheets/ocaml-sodium#48]
We started to use this library extensively at our organization (Ahrefs). This project does not receive any updates for quite a while. Issues are not fixed, PRs are not approved, so currently we maintain a fork at http://github.com/ahrefs/ocaml-sodium with some of the PRs merged.

If there are no objections or better proposals within a reasonable time, we would like to take over the maintenance of the project and publish new releases to opam from our repository.

**Comment by mobileink** [comment]
@cyberhuman  The issues log in your repo is disabled.

**Comment by dsheets** [comment]
Sounds good. I don't object. Sorry for going AWOL. I'm going to archive this repo. Best of luck!
